### ISSUE TITLE
使用中文用户名无法登录

### ISSUE THREAD

**Issue by Daiyangcheng** [LoCyan-Team/LoCyanFrpMSApp#3]
建议检查自己代码的编码问题

如果无法解决建议标明中文用户名使用邮箱登录

以及登录以后从登录接口返回的数据中获取用户名
用户名位于返回json的 userdata.username 字段
这是为了支持邮箱登录做的准备，而又不用修改以前的代码结构

**Comment by XiaMoHuaHuo-CN** [comment]
建议检查自己代码的编码问题

如果无法解决建议标明中文用户名使用邮箱登录

以及登录以后从登录接口返回的数据中获取用户名
用户名位于返回json的 userdata.username 字段
这是为了支持邮箱登录做的准备，而又不用修改以前的代码结构

**Comment by Zhiyuan36** [comment]
已解决，编码问题，正在设计安装包。奖励10TB，不对，dyc...🤣🤣🤣
